/*
 Ras Web Viewer - ver. 2.2.0 - 05.05.2017.
 Copyright Ras Timetable Software. All Rights Reserved.
 http://time-table.net
*/
var U;
(function(a){function d(a){a=c(a);return[parseInt(a.substring(0,2),16),parseInt(a.substring(2,4),16),parseInt(a.substring(4,6),16)]}function c(a){"#"==a.charAt(0)&&(a=a.substring(1,7));6!=a.length&&(a=a.charAt(0)+a.charAt(0)+a.charAt(1)+a.charAt(1)+a.charAt(2)+a.charAt(2));return a}function b(a){return(a=_DB.general.loc[a])?a:""}function e(a){return!isNaN(parseFloat(a))&&isFinite(a)}a.isLtIE9=function(){return document.addEventListener?!1:!0};a.getBrightness=function(a){a=d(a);return(299*a[0]+587*
a[1]+114*a[2])/1E3};a.getRGB=d;a.cutHex=c;a.getPageSize=function(){var a,b;window.innerHeight&&window.scrollMaxY?(a=window.innerWidth+window.scrollMaxX,b=window.innerHeight+window.scrollMaxY):document.body.scrollHeight>document.body.offsetHeight?(a=document.body.scrollWidth,b=document.body.scrollHeight):(a=document.body.offsetWidth,b=document.body.offsetHeight);var c,d;self.innerHeight?(c=document.documentElement.clientWidth?document.documentElement.clientWidth:self.innerWidth,d=self.innerHeight):
document.documentElement&&document.documentElement.clientHeight?(c=document.documentElement.clientWidth,d=document.documentElement.clientHeight):document.body&&(c=document.body.clientWidth,d=document.body.clientHeight);return[a<c?a:c,b<d?d:b,c,d]};a.getLoc=b;a.getDayName=function(a){return b("day"+(a+1))};a.getRealDuration=function(a,b){var c=a+b-_opt.brCas;0<c&&(b-=c);return b};a.getUrlParam=function(a){a=(new RegExp("[?&]"+a+"=([^&#]*)")).exec(window.location.href);return null==a?null:a[1]||0};
a.isNumeric=e;var g="I II III IV V VI VII VIII IX X XI XII".split(" "),f="\u2160\u2161\u2162\u2163\u2164\u2165\u2166\u2167\u2168\u2169\u216a\u216b".split("");a.romanKeyToRomanStr=function(a){var b=a.toUpperCase(),b=g.indexOf(b);return 0<=b?f[b]:a};a.toRomanNum=function(a){var b=parseInt(a,10);if(!e(b)||1>b||12<b)return a;b--;return f[b]}})(U||(U={}));var _DB,_opt,g_blok,g_fontSize,g_$td=null,g_view="",g_rbrs={odel:[],nast:[]};
$(document).ready(function(){if(_DB)if(_DB.err)$("body").append('<div class="error">'+_DB.err+"</div>");else{var a=_DB.general;_opt={brDan:a.day_count,brCas:a.per_count,rbr:a.rbr.split(","),shift:a.shift,bells:a.bells,clRoman:void 0===a.clRoman?!1:a.clRoman,clIndex:void 0===a.clIndex?!0:a.clIndex};var d=U.getLoc("rascas");document.title=d.charAt(0).toLocaleUpperCase()+d.slice(1).toLocaleLowerCase();d=$("#title-left");d.append('<span id="school-name">'+a.school+"</span><br/>");d.append(U.getLoc("skgod")+
" "+a.year+"<br/>");d.append(a.shift);$("#title-center").append("<h1>"+U.getLoc("rascas")+"</h1 >"+U.getLoc("vazi")+" "+a.date);$("label[for=r1]").append(U.getLoc("nast"));$("label[for=r2]").append(U.getLoc("odel"));$("input:radio[name=izbor]").filter('[value="nast"]').prop("checked",!0);$("input:radio[name=izbor]").click(function(a){changeView()});$("#printer").click(function(){printRas();return!1});$("#combo").html('<select id="select" class="tb-item"><option value="nast">'+U.getLoc("nast")+'</option><option value= "odel">'+
U.getLoc("odel")+"</option></select>").change(function(){""!==g_view&&changeView()});a="<table class='mainTable'>"+GetTTHeader(!0);a+=GetTTBody(!0);a+="</table>";$("#raspored_nast").append(a);a="<table class='mainTable'>"+GetTTHeader(!1);a+=GetTTBody(!1);a+="</table>";$("#raspored_odel").append(a);g_blok=_opt.brCas;g_fontSize=90;setFontSize();$(".mainTable th.headCelPer").css("font-size",g_fontSize+"%");$(".mainTable th.headCelPerEven").css("font-size",g_fontSize+"%");$(".mainTable td").not(".rasCelOdel,.rasCelNast,.rbr").css("font-size",
g_fontSize+"%");$(window).resize(function(){waitForFinalEvent(function(){doResize()},500,"some unique string")});$(".mainTable td.rasCelNast, .mainTable td.rasCelOdel").click(function(){loadPopup($(this))});$("div.close").click(function(){disablePopup()});$(this).keyup(function(a){27==a.which&&disablePopup()});$("div#backgroundPopup").click(function(){disablePopup()});$("#screen-container").removeClass("hidden");changeView(U.getUrlParam("v"))}else $("body").append('<div class="error">Ovaj raspored nije objavljen!</div>')});
function changeUrl(a){if("undefined"!=typeof history.replaceState){var d="?pid="+U.getUrlParam("pid")+"&v="+g_view.substr(0,1);a&&(d+="&i="+a);a={Page:$(document).attr("title"),Url:d};history.replaceState(a,a.Page,a.Url)}}function doResize(){setFontSize()&&($(".headCelPer").css("font-size",g_fontSize+"%"),$(".headCelPerEven").css("font-size",g_fontSize+"%"),$(".mainTable td").not(".rasCelOdel,.rasCelNast,.rbr").css("font-size",g_fontSize+"%"));setPopupPos()}
function setFontSize(){var a=[70,100];U.isLtIE9()&&(a=[50,80]);var d=(U.getPageSize()[0]-200)/(_opt.brDan*_opt.brCas),c=g_fontSize;g_fontSize=Math.round(100*d/24*10)/10;g_fontSize>a[1]&&(g_fontSize=a[1]);g_fontSize<a[0]&&(g_fontSize=a[0]);return c!==g_fontSize?!0:!1}var waitForFinalEvent=function(){var a={};return function(d,c,b){b||(b="Don't call this twice without a uniqueId");a[b]&&clearTimeout(a[b]);a[b]=setTimeout(d,c)}}();
function changeView(a){var d=""===g_view;"o"===a&&(g_view="nast");"nast"!==g_view?($("#raspored_odel").hide(),$("#raspored_nast").fadeIn(),g_view="nast",a=$("#nast-name")):($("#raspored_nast").hide(),$("#raspored_odel").fadeIn(),g_view="odel",a=$("#odel-name"));$("input:radio[name=izbor]").filter('[value="'+g_view+'"]').prop("checked",!0);$("#combo").css({top:a.offset().top+2,left:a.offset().left+2});$("#select").css({width:a.width()-3,height:a.height()-3}).val(g_view);d?(a=U.getUrlParam("i"))&&loadPopup(getTD(a),
!0):changeUrl()}function loadPopup(a,d){if(0!==a.length&&!g_$td){g_$td=a;$("#loadme").html(getTooltip());if(d){var c=g_view.substr(0,1)+"_0",c=$("#"+c+" td:nth-child(2)");setPopupPos(c.offset().top+c.height()-5)}else setPopupPos(),changeUrl(getEntyID(g_view,getInd()));$("#toPopup").fadeIn(200);$("#backgroundPopup").css("opacity","0.15");$("#backgroundPopup").fadeIn(200)}}
function setPopupPos(a){if(g_$td){var d=$("#toPopup"),c=70;"nast"!==g_view&&(c=100);c*=_opt.brCas+1;800<c&&(c=800);d.css("width",c);a=void 0!==a?a:g_$td.offset().top+g_$td.height()-5;var b=d.outerHeight(),c=$(document).scrollTop(),b=c+$(window).height()-(a+b);0>b&&(a+=b-5);a<c&&(a=c);var c=g_$td.offset().left+g_$td.width(),e=d.outerWidth(),b=$(document).scrollLeft(),e=b+$(window).width()-(c+e);0>e&&(c+=e-5);c<b&&(c=b);d.css({top:a,left:c})}}
function disablePopup(){g_$td&&($("#toPopup").fadeOut(200),$("#backgroundPopup").fadeOut(200),g_$td=null,changeUrl())}function getEntyID(a,d){if("nast"===a)var c=_DB.teachers,b=4;else c=_DB.classes,b=5;return(c=c[d])&&c[b]?"i"+c[b]:"i"+d}function getTD(a){a=a.substr(1);a=g_view.substr(0,1)+"_"+a;return $("#"+a+" td:nth-child(2)")}function getInd(){var a=g_$td.parent().attr("id");return parseInt(a.substr(2))}
function GetTTHeader(a){var d=_opt.brCas,c="",b;b="<thead><tr>"+("<th class='headCelDay' style='width:20px' rowspan='2'>"+U.getLoc("rbr")+"</th>");a?(b+="<th id='nast-name' class='headCelDay' style='width:10em' rowspan='2'>"+U.getLoc("prez_ime")+"</th>",c="<th class='razmak'></th>"):(b+="<th  id='odel-name' class='headCelDay combo' style='width:5em' rowspan='2'>"+U.getLoc("odel")+"</th>",c="<th class='razmakOdel'></th>");for(a=0;a<_opt.brDan;a++)b+=c,b+="<th",b=0==a%2?b+" class='headCelDayEven'":
b+" class='headCelDay'",b+=" colspan='"+_opt.brCas+"'>",b+=U.getDayName(a),b+="</th>";b+="</tr><tr>";var e;for(a=0;a<_opt.brDan;a++){b+=c;for(var g=0;g<d;g++)e=0==a%2?"headCelPerEven":"headCelPer",b+="<th class='"+e+"'>",b+=_opt.rbr[g],b+="</th>"}return b+"</tr></thead>"}function GetTTBody(a){for(var d="<tbody>",c=a?_DB.teachers:_DB.classes,b=0,e=c.length;b<e;b++)d+=GetTTRow(a,b,c[b]);return d+"</tbody>"}
function GetTTRow(a,d,c){var b,e,g;a?(b="n_"+d,e="rasCelNast",g="<th class='razmak'></th>"):(b="o_"+d,e="rasCelOdel",g="<th class='razmakOdel'></th>");d=""+("<tr class='dataRow' id='"+b+"'>")+("<td class='rbr'>"+(d+1)+".</td>")+("<td class='"+e+"' rel='#loadme'>");d+=a?c[0]:formatClassName(c[0],1);d+="</td>";e=b=0;c=c[3];for(var f=c.length,h=0;h<f;h++){var k=c[h],l=k[0],m=k[1],n=k[2];d+=fillEmpty(b,e,l,m,g);0===m&&(d+=g);d+=getCardHtml(a,k);b=l;e=m;e+=U.getRealDuration(m,n)}d+=fillEmpty(b,e,_opt.brDan-
1,_opt.brCas,g);return d+="</tr>"}function fillEmpty(a,d,c,b,e){var g=_opt.brCas,f="";c=c*g+b;for(a=a*g+d;a<c;a++){d=Math.floor(a/g);b=a%g;0===b&&(f+=e);var h=" class='od'";g>=g?0==d%2&&(h=" class='ev'"):0>=g?0==b%2&&(h=" class='ev'"):0==b/g%2&&(h=" class='ev'");f+="<td"+h+"></td>"}return f}
function getCardHtml(a,d){var c=U.getRealDuration(d[1],d[2]),b="<td";1<c&&(b+=" colspan='"+c+"'");c=d[3];b+="><div>";if($.isArray(c))for(var e=c.length,g=3/e,f=0;f<e;f++){b+="<div style='";b+="line-height:"+g+"em;";b+="height:"+g+"em;";3<e&&(b+="font-size:"+(100-2*e)+"%;");var b=b+"' class='cb",b=b+"'>",h=c[f][0],b=b+(a?formatClassName(_DB.classes[h][0],e):_DB.subjects[h][1]),b=b+"</div>"}else b=b+"<div>"+(a?formatClassName(_DB.classes[c][0],1):_DB.subjects[c][1]),b+="</div>";return b+"</div></td>"}
function formatClassName(a,d){if(!_opt.clRoman&&!_opt.clIndex)return a;var c=a.indexOf("/");0>c&&(c=a.indexOf("-"));if(0<=c){var b=U.romanKeyToRomanStr(a.substr(0,c));_opt.clRoman&&(b=U.toRomanNum(b));if(_opt.clIndex){var e=2<d?"</small>":"</sub>";a=b+(2<d?"<small>":"<sub>")+a.substr(c+1)+e}else a=b+a.substr(c)}return a}
function getTooltip(){var a=g_view,d=getInd(),c=80,b,e;if("nast"===a){12<_opt.brCas&&(c=70);var g=getNastToolCardHTML;b=_DB.teachers[d];a="<h2>"+b[0]+"</h2>";e=b[1];0<=e&&(a+='<div id="toolLeft">'+_DB.subjects[e][0]+"</div>");e=b[2];0<=e&&(a+='<div id="toolRight">'+_DB.general.loc.kabi+": "+_DB.rooms[e][0]+"</div>");e="toolTable"}else g=getOdelToolCardHTML,b=_DB.classes[d],a="<h2>"+formatClassName(b[0],1)+"</h2>",e=b[2],a+='<div id="toolCenter">'+(0<=e?_DB.general.loc.razr+": "+_DB.teachers[e][0]:
"&nbsp")+"</div>",e="toolTable-o";for(var a=a+('<div id="print-tool"><a href="javascript:void(0);" onclick="printRas();">Print</a></div>'+('<table class="'+e+'">'))+"<thead><tr>",a=a+"<th></th>",f=0;f<_opt.brCas;f++)a+="<th>"+_opt.rbr[f],(e=_opt.bells)&&(a+='<br/><span style="font-size:'+c+'%">',""!==e[f][0]&&(a+=e[f][0]+"-"+e[f][1]),""!==e[f][2]&&(a+="<br/>"+e[f][2]+"-"+e[f][3]),a+="</span>"),a+="</th>";a+="</tr>";a+="</thead>";a+="<tbody>";e=b[3];c=0;b=0<e.length?e[0]:null;for(var h=0;h<_opt.brDan;h++){a+=
"<tr>";a+="<th>"+_DB.general.loc["day"+(h+1)].substring(0,3)+"</th>";for(f=0;f<_opt.brCas;f++)null!==b&&b[0]===h&&b[1]===f?(a+=g(b,d),1<b[2]&&(f+=b[2]-1),c++,b=e.length>c?e[c]:null):(a+="<td",g_blok<_opt.brCas&&0<g_blok&&0!==Math.floor(f/g_blok)%2&&(a+=' class="od"'),a+="></td>");a+="</tr>"}a+="</tbody>";return a+"</table>"}
function getNastToolCardHTML(a,d){var c="<td";1<a[2]&&(c+=' colspan="'+a[2]+'"');var c=c+">",b=$.isArray(a[3])?a[3]:[[a[3],-1]],e=36/b.length,g=b[0][0],f=a[4],h=_DB.classes[g][1],g="";f!==_DB.teachers[d][1]&&(g='<span class="pki">'+_DB.subjects[f][1]+"</span>");f='<div class="toolCard" style="background-color:'+h+';"><div class="pk"';128>=U.getBrightness(h)&&(f+=' style="color:white;"');for(var f=f+">"+g+"</div>",k=b.length,l=0;l<k;l++)g=b[l][0],f+='<div class="toolCard_block" style="',f+="background-color:"+
_DB.classes[g][1]+";",f+="line-height:"+e+"px;",f+="height:"+e+"px;",1<k&&(f+="margin:0 1px;"),128>=U.getBrightness(_DB.classes[g][1])&&(f+="color:white;"),f+='">',f+=formatClassName(_DB.classes[g][0],k),0<=b[l][1]&&(f+='<span class="pk">-'+_DB.classes[g][4][b[l][1]]+"</span>"),f+="</div>";b=a[5];e="";0<=b&&b!==_DB.teachers[d][2]&&(e='<span class="pki">'+_DB.rooms[b][1]+"</span>");f+='<div class="pk"';128>=U.getBrightness(h)&&(f+=' style="color:white;"');f+=">";f+=e;f+="</div>";f+="</div>";c+=f;return c+
"</td>"}
function getOdelToolCardHTML(a,d){var c="<td";1<a[2]&&(c+=' colspan="'+a[2]+'"');for(var c=c+'><div class="toolCellOdel">',b=$.isArray(a[3])?a[3]:[[a[3],a[4],-1]],e=6/b.length,g=0;g<b.length;g++){var f=b[g][0],c=c+('<div style="overflow:hidden;height:'+e+"em;background-color:"+_DB.subjects[f][2]+";");128>=U.getBrightness(_DB.subjects[f][2])&&(c+="color:white;");var c=c+'">',h=b[g][1];0<=h&&(c+='<div class="kab"><span class="kab">'+_DB.rooms[h][1]+"</span></div>");c+='<table class="cellTable">';c+=
'<tr><td style="height:'+(e-(0<=h?1:0)).toString()+'em;">';0<=b[g][2]&&(c+='<span class="pk">'+_DB.classes[d][4][b[g][2]]+":");c+=_DB.subjects[f][0]+"</span>";c+="</td></tr></table></div>"}return c+"</div></td>"}function printRas(){var a=g_$td?getToolHeader()+$("#loadme").html():$("#mainFrame").html();$("#print-container").html(a);window.print()}
function getToolHeader(){var a=_DB.general,d;d="<div id='tool-header'><table cellpadding='0' cellspacing='0' width='100%'><tbody><tr><td width='30%'><div class='title' align='left'>"+a.school;d+="<br />"+a.shift;d=d+"</div</td><td width='40%'><div class='title' align='center'>"+("<h3>"+a.loc.rascas+"</h3>");d=d+"</div</td><td width='30%'<div class='title' align='right'>"+(a.loc.skgod+" "+a.year+"<br/>");d+=a.loc.vazi+" "+a.date;return d+"</div</td></tbody></table></div>"};
